selenium-hub:
  image: selenium/hub
  ports:
  - 4446:4444

chrome:
  image: selenium/node-chrome-debug
  ports:
  - 4577
  links:
  - selenium-hub:hub

firefox:
  image: selenium/node-firefox-debug
  ports:
  - 4578
  links:
  - selenium-hub:hub